runtime: php80
env: standard
runtime_config:
  document_root: public

handlers:
- url: /
  script: index.php
# Serve images as static resources.
- url: /(.+\.(gif|png|jpg))$
  static_files: \1
  upload: .+\.(gif|png|jpg)$
  application_readable: true
# Serve php scripts.
- url: /(.+\.php)$
  script: auto



  
  
  